In [27]:
import pandas as pd

# Yeni veri dosyalarını latin-1 ile oku
ratings = pd.read_csv("../data/ratings.dat", sep="::", engine="python",
                      names=["user_id", "movie_id", "rating", "timestamp"],
                      encoding="latin-1")

movies = pd.read_csv("../data/movies.dat", sep="::", engine="python",
                     names=["movie_id", "title", "genres"],
                     encoding="latin-1")

# Birleştir
data = pd.merge(ratings, movies, on="movie_id")

print("✅ Veri başarıyla yüklendi!")
data.head()

✅ Veri başarıyla yüklendi!

,user_id,movie_id,rating,timestamp,title,genres
0,1,1193,5,978300760,One Flew Over the Cuckoo's Nest (1975),Drama
1,1,661,3,978302109,James and the Giant Peach (1996),Animation|Children's|Musical
2,1,914,3,978301968,My Fair Lady (1964),Musical|Romance
3,1,3408,4,978300275,Erin Brockovich (2000),Drama
4,1,2355,5,978824291,"Bug's Life, A (1998)",Animation|Children's|Comedy

In [29]:
# Kullanıcı-Film matrisini oluştur
user_movie_matrix = data.pivot_table(index="user_id", columns="title", values="rating")

print("✅ Kullanıcı-Film matrisi boyutu:", user_movie_matrix.shape)
user_movie_matrix.head()

✅ Kullanıcı-Film matrisi boyutu: (6040, 3706)

title,"$1,000,000 Duck (1971)",'Night Mother (1986),'Til There Was You (1997),"'burbs, The (1989)",...And Justice for All (1979),1-900 (1994),10 Things I Hate About You (1999),101 Dalmatians (1961),101 Dalmatians (1996),12 Angry Men (1957),...,"Young Poisoner's Handbook, The (1995)",Young Sherlock Holmes (1985),Young and Innocent (1937),Your Friends and Neighbors (1998),Zachariah (1971),"Zed & Two Noughts, A (1985)",Zero Effect (1998),Zero Kelvin (Kjærlighetens kjøtere) (1995),Zeus and Roxanne (1997),eXistenZ (1999)
user_id,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Her sütun (film) arasındaki korelasyonu al
movie_similarity = user_movie_matrix.corr(method='pearson', min_periods=50)  # en az 50 ortak kullanıcıya bak

print("✅ Benzerlik matrisi oluşturuldu!")
movie_similarity.head()

✅ Benzerlik matrisi oluşturuldu!

title,'Til There Was You (1997),1-900 (1994),101 Dalmatians (1996),12 Angry Men (1957),187 (1997),2 Days in the Valley (1996),"20,000 Leagues Under the Sea (1954)",2001: A Space Odyssey (1968),3 Ninjas: High Noon At Mega Mountain (1998),"39 Steps, The (1935)",...,Yankee Zulu (1994),Year of the Horse (1997),You So Crazy (1994),Young Frankenstein (1974),Young Guns (1988),Young Guns II (1990),"Young Poisoner's Handbook, The (1995)",Zeus and Roxanne (1997),unknown,Á köldum klaka (Cold Fever) (1994)
title,,,,,,,,,,,,,,,,,,,,,
'Til There Was You (1997),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1-900 (1994),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101 Dalmatians (1996),NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12 Angry Men (1957),NaN,NaN,NaN,1.0,NaN,NaN,NaN,0.178848,NaN,NaN,...,NaN,NaN,NaN,0.096546,NaN,NaN,NaN,NaN,NaN,NaN
187 (1997),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
# Korelasyon matrisi (film-film arası)
movie_similarity = user_movie_matrix.corr(method='pearson', min_periods=30)

print("✅ Benzerlik matrisi oluşturuldu!")
movie_similarity.head()

✅ Benzerlik matrisi oluşturuldu!

title,"$1,000,000 Duck (1971)",'Night Mother (1986),'Til There Was You (1997),"'burbs, The (1989)",...And Justice for All (1979),1-900 (1994),10 Things I Hate About You (1999),101 Dalmatians (1961),101 Dalmatians (1996),12 Angry Men (1957),...,"Young Poisoner's Handbook, The (1995)",Young Sherlock Holmes (1985),Young and Innocent (1937),Your Friends and Neighbors (1998),Zachariah (1971),"Zed & Two Noughts, A (1985)",Zero Effect (1998),Zero Kelvin (Kjærlighetens kjøtere) (1995),Zeus and Roxanne (1997),eXistenZ (1999)
title,,,,,,,,,,,,,,,,,,,,,
"$1,000,000 Duck (1971)",1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Night Mother (1986),NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Til There Was You (1997),NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"'burbs, The (1989)",NaN,NaN,NaN,1.000000,0.089727,NaN,0.189689,0.088541,0.101064,0.047590,...,NaN,0.278425,NaN,0.158997,NaN,NaN,0.039503,NaN,NaN,0.135172
...And Justice for All (1979),NaN,NaN,NaN,0.089727,1.000000,NaN,0.291124,0.166965,-0.142597,0.303093,...,NaN,0.052517,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.024037

In [32]:
def film_öner(film_adi, kaç_tane=10):
    if film_adi not in movie_similarity:
        return f"⚠️ '{film_adi}' adlı film bulunamadı."
    
    benzer_filmler = movie_similarity[film_adi].dropna().sort_values(ascending=False)
    return benzer_filmler.iloc[1:kaç_tane+1]  # kendisini çıkar

In [35]:
film_öner("Toy Story (1995)", 5)

title
Toy Story 2 (1999)       0.630386
Hear My Song (1991)      0.574696
Woman on Top (2000)      0.566103
Polish Wedding (1998)    0.559060
Star Kid (1997)          0.547277
Name: Toy Story (1995), dtype: float64